#!/usr/bin/env python3

import os
import sys
import argparse
import re
import subprocess

verilator_includes_location = "/home/tom/projects/oss-cad-suite/share/verilator/include"

def verilate_modules(modules_list, includes_list):
    command = ["verilator", "--cc"]
    for include in includes_list:
        command.append(f"-I{include}")
    for module in modules_list:
        sub_command = command.copy()
        sub_command.append(module)
        subprocess.call(sub_command)

def make_verilated_libraries(modules_list):
    for module in modules_list:
        filepath = os.path.basename(module)
        filepath, _ = filepath.split(".")
        print(filepath)
        command = ["make", "-f", f"V{filepath}.mk"]
        subprocess.run(command, cwd='./obj_dir')

def build_main_sim(main_src, modules_list, output=None):
    output_file = output if output is not None else main_src.split(".")[0]
    print(output_file)
    command = ["g++"]

    cwd = os.getcwd()

    command.extend([f"-I{cwd}/obj_dir", f"-I{verilator_includes_location}", main_src, f"{verilator_includes_location}/verilated.cpp", f"{verilator_includes_location}/verilated_threads.cpp", "-o", output_file])
    
    for module in modules_list:
        filepath = os.path.basename(module)
        filepath, _ = filepath.split(".")
        filepath = f"libV{filepath}.a"
        command.append(f"{cwd}/obj_dir/{filepath}")

    print(command)
    subprocess.run(command)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--modules", "-m", nargs='+')
    parser.add_argument("--includes", "-I", nargs='+')
    parser.add_argument("src")
    parser.add_argument("--output", "-o")

    args = parser.parse_args()

    modules = args.modules
    verilate_modules(modules, args.includes)
    make_verilated_libraries(modules)
    build_main_sim(args.src, modules, args.output)
